#!/usr/bin/env node
// Station-JS runs one CommonJS file. Inline shared/compute.js (ESM, used by the
// UI too) in front of backend/src/actions.js and write backend/actions.js.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const shared = await readFile(path.join(root, "shared/compute.js"), "utf8");
const actions = await readFile(path.join(root, "backend/src/actions.js"), "utf8");
if (/^\s*import\s/m.test(shared)) throw new Error("shared/compute.js must not import anything");
const inlined = shared.replace(/^export\s+(?=(const|function|async function|class)\s)/gm, "");
if (/^\s*export\s/m.test(inlined)) throw new Error("shared/compute.js uses an export form the backend build cannot inline");
const output = `// GENERATED by scripts/build-backend.mjs from shared/compute.js and backend/src/actions.js.\n// Edit those files, then run \`npm run build:backend\`.\n"use strict";\n\n${inlined}\n${actions}`;
await writeFile(path.join(root, "backend/actions.js"), output);
console.log("built backend/actions.js");
